/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface IActivitiyControlsRequest {
    activityTypeId?: number;
    activityDataId?: number;
}


export class ActivitiyControlsRequest extends BaseModel implements IActivitiyControlsRequest  {

    static ACTIVITY_TYPE_ID_FIELD_NAME = 'activityTypeId';
    static ACTIVITY_DATA_ID_FIELD_NAME = 'activityDataId';

    activityTypeId: number;
    activityDataId: number;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.activityTypeId = rawValues.activityTypeId;
            this.activityDataId = rawValues.activityDataId;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                activityTypeId: new FormControl(this.activityTypeId),
                activityDataId: new FormControl(this.activityDataId),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls[ActivitiyControlsRequest.ACTIVITY_TYPE_ID_FIELD_NAME].setValue(this.activityTypeId);
        this.$formGroup.controls[ActivitiyControlsRequest.ACTIVITY_DATA_ID_FIELD_NAME].setValue(this.activityDataId);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

