/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { CustomerTypeItemModel } from './customer-type-item-model.model';

export interface ICustomerTypeModelList {
    showDeleted?: boolean;
    commercialEntityTypes?: Array<CustomerTypeItemModel>;
    filter?: string;
    formAction?: string;
    itemsPerPage?: number;
    itemsCount?: number;
    pageIndex?: number;
    pageCount?: number;
    newSort?: string;
}


export class CustomerTypeModelList extends BaseModel implements ICustomerTypeModelList  {

    static SHOW_DELETED_FIELD_NAME = 'showDeleted';
    static COMMERCIAL_ENTITY_TYPES_FIELD_NAME = 'commercialEntityTypes';
    static FILTER_FIELD_NAME = 'filter';
    static FORM_ACTION_FIELD_NAME = 'formAction';
    static ITEMS_PER_PAGE_FIELD_NAME = 'itemsPerPage';
    static ITEMS_COUNT_FIELD_NAME = 'itemsCount';
    static PAGE_INDEX_FIELD_NAME = 'pageIndex';
    static PAGE_COUNT_FIELD_NAME = 'pageCount';
    static NEW_SORT_FIELD_NAME = 'newSort';

    showDeleted: boolean;
    commercialEntityTypes: Array<CustomerTypeItemModel>;
    filter: string;
    formAction: string;
    itemsPerPage: number;
    itemsCount: number;
    pageIndex: number;
    pageCount: number;
    newSort: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();
        this.commercialEntityTypes = new Array<CustomerTypeItemModel>(); 

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.showDeleted = rawValues.showDeleted;
            this.fillModelArray<CustomerTypeItemModel>(this, CustomerTypeModelList.COMMERCIAL_ENTITY_TYPES_FIELD_NAME, rawValues.commercialEntityTypes, useFormGroupValuesToModel, CustomerTypeItemModel, SubTypeFactory.createSubTypeInstance);
            this.filter = rawValues.filter;
            this.formAction = rawValues.formAction;
            this.itemsPerPage = rawValues.itemsPerPage;
            this.itemsCount = rawValues.itemsCount;
            this.pageIndex = rawValues.pageIndex;
            this.pageCount = rawValues.pageCount;
            this.newSort = rawValues.newSort;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                showDeleted: new FormControl(this.showDeleted),
                commercialEntityTypes: new FormArray([]),
                filter: new FormControl(this.filter),
                formAction: new FormControl(this.formAction),
                itemsPerPage: new FormControl(this.itemsPerPage),
                itemsCount: new FormControl(this.itemsCount),
                pageIndex: new FormControl(this.pageIndex),
                pageCount: new FormControl(this.pageCount),
                newSort: new FormControl(this.newSort),
            });
            // generate FormArray control elements
            this.fillFormArray<CustomerTypeItemModel>(CustomerTypeModelList.COMMERCIAL_ENTITY_TYPES_FIELD_NAME, this.commercialEntityTypes, CustomerTypeItemModel);
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls[CustomerTypeModelList.SHOW_DELETED_FIELD_NAME].setValue(this.showDeleted);
        this.fillFormArray<CustomerTypeItemModel>(CustomerTypeModelList.COMMERCIAL_ENTITY_TYPES_FIELD_NAME, this.commercialEntityTypes, CustomerTypeItemModel);
        this.$formGroup.controls[CustomerTypeModelList.FILTER_FIELD_NAME].setValue(this.filter);
        this.$formGroup.controls[CustomerTypeModelList.FORM_ACTION_FIELD_NAME].setValue(this.formAction);
        this.$formGroup.controls[CustomerTypeModelList.ITEMS_PER_PAGE_FIELD_NAME].setValue(this.itemsPerPage);
        this.$formGroup.controls[CustomerTypeModelList.ITEMS_COUNT_FIELD_NAME].setValue(this.itemsCount);
        this.$formGroup.controls[CustomerTypeModelList.PAGE_INDEX_FIELD_NAME].setValue(this.pageIndex);
        this.$formGroup.controls[CustomerTypeModelList.PAGE_COUNT_FIELD_NAME].setValue(this.pageCount);
        this.$formGroup.controls[CustomerTypeModelList.NEW_SORT_FIELD_NAME].setValue(this.newSort);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

