/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface ICustomFieldItemModel {
    id?: number;
    name?: string;
    dataType?: string;
    mandatory?: boolean;
    help?: string;
    code?: string;
    order?: number;
}


export class CustomFieldItemModel extends BaseModel implements ICustomFieldItemModel  {

    static ID_FIELD_NAME = 'id';
    static NAME_FIELD_NAME = 'name';
    static DATA_TYPE_FIELD_NAME = 'dataType';
    static MANDATORY_FIELD_NAME = 'mandatory';
    static HELP_FIELD_NAME = 'help';
    static CODE_FIELD_NAME = 'code';
    static ORDER_FIELD_NAME = 'order';

    id: number;
    name: string;
    dataType: string;
    mandatory: boolean;
    help: string;
    code: string;
    order: number;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.id = rawValues.id;
            this.name = rawValues.name;
            this.dataType = rawValues.dataType;
            this.mandatory = rawValues.mandatory;
            this.help = rawValues.help;
            this.code = rawValues.code;
            this.order = rawValues.order;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                id: new FormControl(this.id),
                name: new FormControl(this.name),
                dataType: new FormControl(this.dataType),
                mandatory: new FormControl(this.mandatory),
                help: new FormControl(this.help),
                code: new FormControl(this.code),
                order: new FormControl(this.order),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls[CustomFieldItemModel.ID_FIELD_NAME].setValue(this.id);
        this.$formGroup.controls[CustomFieldItemModel.NAME_FIELD_NAME].setValue(this.name);
        this.$formGroup.controls[CustomFieldItemModel.DATA_TYPE_FIELD_NAME].setValue(this.dataType);
        this.$formGroup.controls[CustomFieldItemModel.MANDATORY_FIELD_NAME].setValue(this.mandatory);
        this.$formGroup.controls[CustomFieldItemModel.HELP_FIELD_NAME].setValue(this.help);
        this.$formGroup.controls[CustomFieldItemModel.CODE_FIELD_NAME].setValue(this.code);
        this.$formGroup.controls[CustomFieldItemModel.ORDER_FIELD_NAME].setValue(this.order);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

